import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    'intro',
    'official-deployments-addresses/README',
    {
      type: 'category',
      label: 'Contracts & Oracles',
      items: [
        'smart-contracts/ktv2factory-contract',
        'smart-contracts/ktv2-contract',
        'smart-contracts/tokenprice-contract',
        'smart-contracts/chainlink-oracle',
        'smart-contracts/timelock-contract',
      ],
    },
    {
      type: 'category',
      label: 'Off-Chain Nodes',
      items: [
        'node/ktoc',
        'node/cloud-setup',
        'node/vote-and-reward',
        'node/fee',
        'node/application',
      ],
    },
    'charity/README',
    {
      type: 'category',
      label: 'dApp Technical Overview',
      items: [
        'dapp-technical-overview/architecture-and-codebase',
        'dapp-technical-overview/api-reference',
      ],
    },
    {
      type: 'category',
      label: 'Telegram Bot',
      link: {
        type: 'doc',
        id: 'telegram-bot/README',
      },
      items: [
      ],
    },
  ],
};

export default sidebars;
